# Generated by Django 5.2.15 on 2026-07-03 15:06

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='users/profiles/default-avatar.png', null=True, upload_to=apps.accounts.models.user_profile_image_path, verbose_name='عکس پروفایل'),
        ),
    ]
