# Generated by Django 5.2.15 on 2026-07-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='توضیحات درباره نویسنده برای نمایش در انتهای مقاله', null=True, verbose_name='بیوگرافی'),
        ),
    ]
