# Generated by Django 5.2.15 on 2026-07-07 17:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('none', 'ترجیح می\u200cدهم نگویم')], default='none', max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='کد ملی'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='accounts.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['name'],
                'unique_together': {('province', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='نام گیرنده')),
                ('recipient_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره موبایل معتبر نیست')], verbose_name='شماره موبایل گیرنده')),
                ('address', models.TextField(verbose_name='آدرس کامل')),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='کد پستی')),
                ('plaque', models.CharField(max_length=20, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='طبقه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات اضافی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.city', verbose_name='شهر')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
