# Generated by Django 5.2.15 on 2026-09-07 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[\\w\\s\u0600-ۿ\u200c.'\\-]+$", 'نام فقط می\u200cتواند شامل حروف، عدد، فاصله و نشانه\u200cهای . - باشد')], verbose_name='نام کامل'),
        ),
    ]
