# Generated by Django 5.2.15 on 2026-07-15 11:20

import apps.home.models
import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='عنوان صفحه در نتایج جستجو (حداکثر ۶۰ کاراکتر)', max_length=60, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, help_text='توضیحات صفحه در نتایج جستجو (حداکثر ۱۶۰ کاراکتر)', max_length=160, verbose_name='توضیحات متا')),
                ('hero_title_part1', models.CharField(default='متفاوت', max_length=100, verbose_name='بخش اول عنوان هیرو')),
                ('hero_title_part2', models.CharField(default='برقی', max_length=100, verbose_name='بخش دوم عنوان هیرو (رنگی)')),
                ('hero_title_part3', models.CharField(default='برانید', max_length=100, verbose_name='بخش سوم عنوان هیرو')),
                ('hero_tag', models.CharField(default='آینده جابه\u200cجایی شهری', max_length=200, verbose_name='تگ هیرو')),
                ('hero_description', models.TextField(default='اسکوترهای برقی پریمیوم، طراحی\u200cشده برای کسانی که بیشتر می\u200cخواهند. ساخته\u200cشده با دقت، هدایت\u200cشده با عملکرد.', verbose_name='توضیحات هیرو')),
                ('hero_btn_text', models.CharField(default='مشاهده مجموعه', max_length=100, verbose_name='متن دکمه اصلی')),
                ('hero_btn_secondary_text', models.CharField(default='کاوش مدل\u200cها', max_length=100, verbose_name='متن دکمه ثانویه')),
                ('hero_image', models.ImageField(blank=True, help_text='تصویر اصلی هیرو (Desktop)\n📐 ابعاد: 1200 × 800 پیکسل\n📁 فرمت: WebP یا JPEG', null=True, upload_to='home/index/hero/', verbose_name='تصویر هیرو')),
                ('hero_mobile_image', models.ImageField(blank=True, help_text='تصویر هیرو برای موبایل\n📐 ابعاد: 600 × 400 پیکسل', null=True, upload_to='home/index/hero/', verbose_name='تصویر هیرو موبایل')),
                ('hero_image_alt', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین تصویر هیرو')),
                ('hero_stat_1_value', models.CharField(default='85', max_length=50, verbose_name='مقدار آمار ۱')),
                ('hero_stat_1_unit', models.CharField(blank=True, default='km/h', max_length=20, verbose_name='واحد آمار ۱')),
                ('hero_stat_1_label', models.CharField(default='حداکثر سرعت', max_length=50, verbose_name='برچسب آمار ۱')),
                ('hero_stat_2_value', models.CharField(default='160', max_length=50, verbose_name='مقدار آمار ۲')),
                ('hero_stat_2_unit', models.CharField(blank=True, default='km', max_length=20, verbose_name='واحد آمار ۲')),
                ('hero_stat_2_label', models.CharField(default='برد', max_length=50, verbose_name='برچسب آمار ۲')),
                ('hero_stat_3_value', models.CharField(default='2', max_length=50, verbose_name='مقدار آمار ۳')),
                ('hero_stat_3_unit', models.CharField(blank=True, default='hr', max_length=20, verbose_name='واحد آمار ۳')),
                ('hero_stat_3_label', models.CharField(default='زمان شارژ', max_length=50, verbose_name='برچسب آمار ۳')),
                ('hero_stat_4_value', models.CharField(default='40k', max_length=50, verbose_name='مقدار آمار ۴')),
                ('hero_stat_4_unit', models.CharField(blank=True, default='+', max_length=20, verbose_name='واحد آمار ۴')),
                ('hero_stat_4_label', models.CharField(default='کاربران', max_length=50, verbose_name='برچسب آمار ۴')),
                ('best_sellers_label', models.CharField(default='پرفروش\u200cترین\u200cها', max_length=100, verbose_name='برچسب بخش پرفروش\u200cها')),
                ('best_sellers_title', models.CharField(default='برترین انتخاب\u200cهای این فصل', max_length=200, verbose_name='عنوان بخش پرفروش\u200cها')),
                ('testimonials_label', models.CharField(default='نظرات', max_length=100, verbose_name='برچسب بخش نظرات')),
                ('testimonials_title', models.CharField(default='کاربران چه می\u200cگویند', max_length=200, verbose_name='عنوان بخش نظرات')),
                ('testimonials_rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3, verbose_name='میانگین امتیاز')),
                ('testimonials_count', models.CharField(default='40k', max_length=50, verbose_name='تعداد نظرات')),
                ('testimonials_count_label', models.CharField(default='کاربران راضی', max_length=100, verbose_name='برچسب تعداد نظرات')),
                ('guide_label', models.CharField(default='منابع', max_length=100, verbose_name='برچسب بخش راهنما')),
                ('guide_title', models.CharField(default='راهنمای کامل خرید', max_length=200, verbose_name='عنوان بخش راهنما')),
                ('promise_label', models.CharField(default='چرا VOLTEX', max_length=100, verbose_name='برچسب بخش تعهدات')),
                ('promise_title', models.CharField(default='تعهد VOLTEX', max_length=200, verbose_name='عنوان بخش تعهدات')),
                ('statement_eyebrow', models.CharField(default='سفر شما از اینجا آغاز می\u200cشود', max_length=200, verbose_name='زیر عنوان بیانیه پایانی')),
                ('statement_title', models.CharField(default='امروز جلوتر برو', max_length=200, verbose_name='عنوان بیانیه پایانی')),
                ('statement_title_highlight', models.CharField(default='جلوتر', max_length=100, verbose_name='کلمه برجسته در بیانیه پایانی')),
                ('statement_description', models.TextField(default='به بیش از ۴۰,۰۰۰ راکب در سراسر اروپا بپیوندید که Voltex را انتخاب کرده\u200cاند. اسکوترهای پریمیوم، تحویل در ۲۴ ساعت، با ۳ سال گارانتی.', verbose_name='توضیحات بیانیه پایانی')),
                ('statement_btn_text', models.CharField(default='مشاهده همه مدل\u200cها', max_length=100, verbose_name='متن دکمه اصلی بیانیه پایانی')),
                ('statement_btn_secondary_text', models.CharField(default='کاوش مجموعه\u200cها', max_length=100, verbose_name='متن دکمه ثانویه بیانیه پایانی')),
                ('footer_tagline', models.CharField(default='اسکوترهای برقی پریمیوم، طراحی\u200cشده برای کسانی که بیشتر می\u200cخواهند.', max_length=200, verbose_name='شعار فوتر')),
                ('footer_copyright', models.CharField(default='© ۲۰۲۶ Voltex GmbH. تمامی حقوق محفوظ است.', max_length=200, verbose_name='متن کپی\u200cرایت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه اصلی',
                'verbose_name_plural': 'تنظیمات صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_svg', models.TextField(blank=True, help_text='کد SVG آیکون', verbose_name='SVG آیکون')),
                ('label', models.CharField(max_length=50, verbose_name='برچسب')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('badge_value', models.CharField(max_length=50, verbose_name='مقدار نشان')),
                ('badge_unit', models.CharField(blank=True, max_length=20, verbose_name='واحد نشان')),
                ('color', models.CharField(choices=[('neon', '#4fd8ff'), ('orange', '#ff9a3c'), ('green', '#a8e063'), ('neon2', '#8b7bff'), ('neon3', '#ff6cc4')], default='neon', max_length=20, verbose_name='رنگ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تعهد',
                'verbose_name_plural': 'تعهدات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('quote', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='امتیاز')),
                ('avatar_color_start', models.CharField(choices=[('neon', '#4fd8ff'), ('orange', '#ff9a3c'), ('green', '#a8e063'), ('neon2', '#8b7bff'), ('neon3', '#ff6cc4')], default='neon', max_length=20, verbose_name='رنگ شروع آواتار')),
                ('avatar_color_end', models.CharField(choices=[('neon', '#4fd8ff'), ('orange', '#ff9a3c'), ('green', '#a8e063'), ('neon2', '#8b7bff'), ('neon3', '#ff6cc4')], default='neon2', max_length=20, verbose_name='رنگ پایان آواتار')),
                ('avatar_image', models.ImageField(blank=True, help_text='ابعاد پیشنهادی: 200×200 پیکسل، مربع', null=True, upload_to='home/testimonials/avatars/', verbose_name='عکس پروفایل')),
                ('avatar_initials', models.CharField(blank=True, max_length=5, verbose_name='حروف اول (اگر خالی باشد از نام گرفته می\u200cشود)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نظر ویژه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات صفحه اصلی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='اسلاگ')),
                ('description', ckeditor.fields.RichTextField(verbose_name='محتوا')),
                ('excerpt', models.TextField(blank=True, help_text='خلاصه\u200cای از مقاله که در کارت\u200cها و متا دیسکریپشن نمایش داده می\u200cشود. اگر خالی باشد، از ۱۵۰ کاراکتر اول description استفاده می\u200cشود.', max_length=300, verbose_name='خلاصه')),
                ('cover_image', models.ImageField(blank=True, help_text='تصویر اصلی مقاله که در هدر و کارت\u200cها نمایش داده می\u200cشود.\n📐 ابعاد: 1200 × 630 پیکسل (نسبت 1.91:1)\n📁 فرمت: WebP (بهترین) یا JPEG\n📦 حجم: حداکثر 200 کیلوبایت\n🖥️ رزولوشن: 72 DPI (مناسب برای وب)', null=True, upload_to='home/articles/', verbose_name='تصویر کاور')),
                ('cover_alt_text', models.CharField(blank=True, help_text='برای سئو و دسترسی\u200cپذیری', max_length=200, verbose_name='متن جایگزین تصویر')),
                ('attachment', models.FileField(blank=True, help_text='فرمت\u200cهای مجاز: png, jpg, webp, mp4, mp3, pdf — حداکثر ۲۵ مگابایت', null=True, upload_to=apps.home.models.article_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'mp4', 'mp3', 'pdf']), apps.home.models.validate_attachment_size, apps.home.models.validate_attachment_content])),
                ('time_to_read', models.PositiveSmallIntegerField(blank=True, help_text='اگر خالی باشد، به\u200cطور خودکار از روی محتوا محاسبه می\u200cشود', null=True, verbose_name='زمان مطالعه (دقیقه)')),
                ('meta_description', models.CharField(blank=True, help_text='اگر خالی باشد، از excerpt استفاده می\u200cشود', max_length=160, verbose_name='متا دیسکریپشن')),
                ('meta_keywords', models.CharField(blank=True, help_text='با کاما جدا کنید', max_length=200, verbose_name='کلمات کلیدی')),
                ('canonical_url', models.URLField(blank=True, help_text='اگر خالی باشد، لینک خود مقاله استفاده می\u200cشود', verbose_name='لینک کنونیکال')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(blank=True, help_text='اگر خالی باشد و is_published=True باشد، زمان ایجاد استفاده می\u200cشود', null=True, verbose_name='زمان انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='home.tag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='برچسب')),
                ('badge_text', models.CharField(blank=True, max_length=100, verbose_name='متن نشان')),
                ('color', models.CharField(choices=[('cyan', '#00f0ff'), ('orange', '#f97316'), ('red', '#ef4444'), ('yellow', '#fbbf24'), ('purple', '#a855f7'), ('green', '#22c55e')], default='cyan', max_length=20, verbose_name='رنگ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='shop.category')),
            ],
            options={
                'verbose_name': 'نشان دسته\u200cبندی',
                'verbose_name_plural': 'نشان\u200cهای دسته\u200cبندی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CategoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='آیکون فونت\u200cآ\u200cوسم یا ایموجی', max_length=50, verbose_name='آیکون')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
                ('label', models.CharField(max_length=100, verbose_name='برچسب')),
                ('color', models.CharField(choices=[('cyan', '#00f0ff'), ('orange', '#f97316'), ('red', '#ef4444'), ('yellow', '#fbbf24'), ('purple', '#a855f7'), ('green', '#22c55e')], default='cyan', max_length=20, verbose_name='رنگ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shop.category')),
            ],
            options={
                'verbose_name': 'ویژگی دسته\u200cبندی',
                'verbose_name_plural': 'ویژگی\u200cهای دسته\u200cبندی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('is_primary', models.BooleanField(default=True, verbose_name='تصویر اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.category')),
            ],
            options={
                'verbose_name': 'تصویر دسته\u200cبندی',
                'verbose_name_plural': 'تصاویر دسته\u200cبندی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.article', verbose_name='مقاله')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.comment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='متن نشان')),
                ('color', models.CharField(choices=[('neon', '#4fd8ff'), ('orange', '#ff9a3c'), ('green', '#a8e063'), ('neon2', '#8b7bff'), ('neon3', '#ff6cc4')], default='neon', max_length=20, verbose_name='رنگ تم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_cards', to='shop.product')),
            ],
            options={
                'verbose_name': 'کارت محصول',
                'verbose_name_plural': 'کارت\u200cهای محصول',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at', 'is_published'], name='home_articl_created_c1a72f_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='home_articl_slug_68c365_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', '-published_at'], name='home_articl_is_publ_2ee095_idx'),
        ),
    ]
