# Generated by Django 5.2.15 on 2026-07-17 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='comment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='در صورت رد شدن نظر، دلیل آن را وارد کنید', verbose_name='دلیل رد شدن'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'status', 'parent'], name='home_commen_article_eb2a3a_idx'),
        ),
    ]
