# Generated by Django 5.2.15 on 2026-07-03 15:06

import apps.home.models
import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='اگر خالی باشد، لینک خود مقاله استفاده می\u200cشود', verbose_name='لینک کنونیکال'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_alt_text',
            field=models.CharField(blank=True, help_text='برای سئو و دسترسی\u200cپذیری', max_length=200, verbose_name='متن جایگزین تصویر'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='تصویر اصلی مقاله که در هدر و کارت\u200cها نمایش داده می\u200cشود', null=True, upload_to='blog/covers/', verbose_name='تصویر شاخص'),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='خلاصه\u200cای از مقاله که در کارت\u200cها و متا دیسکریپشن نمایش داده می\u200cشود. اگر خالی باشد، از ۱۵۰ کاراکتر اول description استفاده می\u200cشود.', max_length=300, verbose_name='خلاصه'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='اگر خالی باشد، از excerpt استفاده می\u200cشود', max_length=160, verbose_name='متا دیسکریپشن'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='با کاما جدا کنید', max_length=200, verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='اگر خالی باشد و is_published=True باشد، زمان ایجاد استفاده می\u200cشود', null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='article',
            name='attachment',
            field=models.FileField(blank=True, help_text='فرمت\u200cهای مجاز: png, jpg, webp, mp4, mp3, pdf — حداکثر ۲۵ مگابایت', null=True, upload_to=apps.home.models.article_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'mp4', 'mp3', 'pdf']), apps.home.models.validate_attachment_size, apps.home.models.validate_attachment_content]),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='منتشر شده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='home.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time_to_read',
            field=models.PositiveSmallIntegerField(blank=True, help_text='اگر خالی باشد، به\u200cطور خودکار از روی محتوا محاسبه می\u200cشود', null=True, verbose_name='زمان مطالعه (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='home_articl_slug_68c365_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', '-published_at'], name='home_articl_is_publ_2ee095_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.article', verbose_name='مقاله'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.comment', verbose_name='پاسخ به'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
