# Generated by Django 5.2.15 on 2026-07-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment_alter_article_options_article_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='تصویر اصلی مقاله که در هدر و کارت\u200cها نمایش داده می\u200cشود.\n📐 ابعاد: 1200 × 630 پیکسل (نسبت 1.91:1)\n📁 فرمت: WebP (بهترین) یا JPEG\n📦 حجم: حداکثر 200 کیلوبایت\n🖥️ رزولوشن: 72 DPI (مناسب برای وب)', null=True, upload_to='home/articles/', verbose_name='تصویر کاور'),
        ),
    ]
