# Generated by Django 5.2.15 on 2026-07-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_comment_is_approved_comment_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpagesettings',
            name='footer_copyright',
        ),
        migrations.RemoveField(
            model_name='indexpagesettings',
            name='footer_tagline',
        ),
    ]
