# Generated by Django 5.2.15 on 2026-07-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_indexpagesettings_footer_copyright_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpagesettings',
            name='hero_stat_1_unit',
            field=models.CharField(blank=True, default='km/h', max_length=20, null=True, verbose_name='واحد آمار ۱'),
        ),
    ]
