# Generated by Django 5.2.15 on 2026-07-05 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_article_cover_image'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='عنوان صفحه در نتایج جستجو (حداکثر ۶۰ کاراکتر)', max_length=60, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, help_text='توضیحات صفحه در نتایج جستجو (حداکثر ۱۶۰ کاراکتر)', max_length=160, verbose_name='توضیحات متا')),
                ('hero_title_part1', models.CharField(default='متفاوت', max_length=100, verbose_name='بخش اول عنوان هیرو')),
                ('hero_title_part2', models.CharField(default='برقی', max_length=100, verbose_name='بخش دوم عنوان هیرو (رنگی)')),
                ('hero_title_part3', models.CharField(default='برانید', max_length=100, verbose_name='بخش سوم عنوان هیرو')),
                ('hero_tag', models.CharField(default='آینده جابه\u200cجایی شهری', max_length=200, verbose_name='تگ هیرو')),
                ('hero_description', models.TextField(default='اسکوترهای برقی پریمیوم، طراحی\u200cشده برای کسانی که بیشتر می\u200cخواهند. ساخته\u200cشده با دقت، هدایت\u200cشده با عملکرد.', verbose_name='توضیحات هیرو')),
                ('hero_btn_text', models.CharField(default='مشاهده مجموعه', max_length=100, verbose_name='متن دکمه اصلی')),
                ('hero_btn_secondary_text', models.CharField(default='کاوش مدل\u200cها', max_length=100, verbose_name='متن دکمه ثانویه')),
                ('hero_image', models.ImageField(blank=True, help_text='تصویر اصلی هیرو (Desktop)\n📐 ابعاد: 1200 × 800 پیکسل\n📁 فرمت: WebP یا JPEG', null=True, upload_to='home/index/hero/', verbose_name='تصویر هیرو')),
                ('hero_mobile_image', models.ImageField(blank=True, help_text='تصویر هیرو برای موبایل\n📐 ابعاد: 600 × 400 پیکسل', null=True, upload_to='home/index/hero/', verbose_name='تصویر هیرو موبایل')),
                ('hero_image_alt', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین تصویر هیرو')),
                ('hero_stat_1_value', models.CharField(default='85', max_length=50, verbose_name='مقدار آمار ۱')),
                ('hero_stat_1_unit', models.CharField(blank=True, default='km/h', max_length=20, verbose_name='واحد آمار ۱')),
                ('hero_stat_1_label', models.CharField(default='حداکثر سرعت', max_length=50, verbose_name='برچسب آمار ۱')),
                ('hero_stat_2_value', models.CharField(default='160', max_length=50, verbose_name='مقدار آمار ۲')),
                ('hero_stat_2_unit', models.CharField(blank=True, default='km', max_length=20, verbose_name='واحد آمار ۲')),
                ('hero_stat_2_label', models.CharField(default='برد', max_length=50, verbose_name='برچسب آمار ۲')),
                ('hero_stat_3_value', models.CharField(default='2', max_length=50, verbose_name='مقدار آمار ۳')),
                ('hero_stat_3_unit', models.CharField(blank=True, default='hr', max_length=20, verbose_name='واحد آمار ۳')),
                ('hero_stat_3_label', models.CharField(default='زمان شارژ', max_length=50, verbose_name='برچسب آمار ۳')),
                ('hero_stat_4_value', models.CharField(default='40k', max_length=50, verbose_name='مقدار آمار ۴')),
                ('hero_stat_4_unit', models.CharField(blank=True, default='+', max_length=20, verbose_name='واحد آمار ۴')),
                ('hero_stat_4_label', models.CharField(default='کاربران', max_length=50, verbose_name='برچسب آمار ۴')),
                ('best_sellers_label', models.CharField(default='پرفروش\u200cترین\u200cها', max_length=100, verbose_name='برچسب بخش پرفروش\u200cها')),
                ('best_sellers_title', models.CharField(default='برترین انتخاب\u200cهای این فصل', max_length=200, verbose_name='عنوان بخش پرفروش\u200cها')),
                ('testimonials_label', models.CharField(default='نظرات', max_length=100, verbose_name='برچسب بخش نظرات')),
                ('testimonials_title', models.CharField(default='کاربران چه می\u200cگویند', max_length=200, verbose_name='عنوان بخش نظرات')),
                ('testimonials_rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3, verbose_name='میانگین امتیاز')),
                ('testimonials_count', models.CharField(default='40k', max_length=50, verbose_name='تعداد نظرات')),
                ('testimonials_count_label', models.CharField(default='کاربران راضی', max_length=100, verbose_name='برچسب تعداد نظرات')),
                ('guide_label', models.CharField(default='منابع', max_length=100, verbose_name='برچسب بخش راهنما')),
                ('guide_title', models.CharField(default='راهنمای کامل خرید', max_length=200, verbose_name='عنوان بخش راهنما')),
                ('promise_label', models.CharField(default='چرا VOLTEX', max_length=100, verbose_name='برچسب بخش تعهدات')),
                ('promise_title', models.CharField(default='تعهد VOLTEX', max_length=200, verbose_name='عنوان بخش تعهدات')),
                ('statement_eyebrow', models.CharField(default='سفر شما از اینجا آغاز می\u200cشود', max_length=200, verbose_name='زیر عنوان بیانیه پایانی')),
                ('statement_title', models.CharField(default='امروز جلوتر برو', max_length=200, verbose_name='عنوان بیانیه پایانی')),
                ('statement_title_highlight', models.CharField(default='جلوتر', max_length=100, verbose_name='کلمه برجسته در بیانیه پایانی')),
                ('statement_description', models.TextField(default='به بیش از ۴۰,۰۰۰ راکب در سراسر اروپا بپیوندید که Voltex را انتخاب کرده\u200cاند. اسکوترهای پریمیوم، تحویل در ۲۴ ساعت، با ۳ سال گارانتی.', verbose_name='توضیحات بیانیه پایانی')),
                ('statement_btn_text', models.CharField(default='مشاهده همه مدل\u200cها', max_length=100, verbose_name='متن دکمه اصلی بیانیه پایانی')),
                ('statement_btn_secondary_text', models.CharField(default='کاوش مجموعه\u200cها', max_length=100, verbose_name='متن دکمه ثانویه بیانیه پایانی')),
                ('footer_tagline', models.CharField(default='اسکوترهای برقی پریمیوم، طراحی\u200cشده برای کسانی که بیشتر می\u200cخواهند.', max_length=200, verbose_name='شعار فوتر')),
                ('footer_copyright', models.CharField(default='© ۲۰۲۶ Voltex GmbH. تمامی حقوق محفوظ است.', max_length=200, verbose_name='متن کپی\u200cرایت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه اصلی',
                'verbose_name_plural': 'تنظیمات صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_svg', models.TextField(blank=True, help_text='کد SVG آیکون', verbose_name='SVG آیکون')),
                ('label', models.CharField(max_length=50, verbose_name='برچسب')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('badge_value', models.CharField(max_length=50, verbose_name='مقدار نشان')),
                ('badge_unit', models.CharField(blank=True, max_length=20, verbose_name='واحد نشان')),
                ('color', models.CharField(choices=[('neon', '#4fd8ff'), ('orange', '#ff9a3c'), ('green', '#a8e063'), ('neon2', '#8b7bff'), ('neon3', '#ff6cc4')], default='neon', max_length=20, verbose_name='رنگ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تعهد',
                'verbose_name_plural': 'تعهدات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('quote', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='امتیاز')),
                ('avatar_color_start', models.CharField(default='neon', max_length=20, verbose_name='رنگ شروع آواتار')),
                ('avatar_color_end', models.CharField(default='neon2', max_length=20, verbose_name='رنگ پایان آواتار')),
                ('avatar_initials', models.CharField(blank=True, max_length=5, verbose_name='حروف اول (اگر خالی باشد از نام گرفته می\u200cشود)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نظر ویژه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات صفحه اصلی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CategoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='برچسب ویژگی')),
                ('value', models.CharField(max_length=50, verbose_name='مقدار ویژگی')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد')),
                ('color', models.CharField(choices=[('neon', '#4fd8ff'), ('orange', '#ff9a3c'), ('green', '#a8e063'), ('neon2', '#8b7bff'), ('neon3', '#ff6cc4')], default='neon', max_length=20, verbose_name='رنگ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_features', to='shop.category')),
            ],
            options={
                'verbose_name': 'ویژگی دسته\u200cبندی',
                'verbose_name_plural': 'ویژگی\u200cهای دسته\u200cبندی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='متن نشان')),
                ('color', models.CharField(choices=[('neon', '#4fd8ff'), ('orange', '#ff9a3c'), ('green', '#a8e063'), ('neon2', '#8b7bff'), ('neon3', '#ff6cc4')], default='neon', max_length=20, verbose_name='رنگ تم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_cards', to='shop.product')),
            ],
            options={
                'verbose_name': 'کارت محصول',
                'verbose_name_plural': 'کارت\u200cهای محصول',
                'ordering': ['order'],
            },
        ),
    ]
