# Generated by Django 5.2.15 on 2026-07-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_indexpagesettings_hero_stat_1_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfeature',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
