# Generated by Django 5.2.15 on 2026-07-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_indexpagesettings_promise_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text='ابعاد پیشنهادی: 200×200 پیکسل، مربع', null=True, upload_to='home/testimonials/avatars/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar_color_end',
            field=models.CharField(choices=[('neon', '#4fd8ff'), ('orange', '#ff9a3c'), ('green', '#a8e063'), ('neon2', '#8b7bff'), ('neon3', '#ff6cc4')], default='neon2', max_length=20, verbose_name='رنگ پایان آواتار'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar_color_start',
            field=models.CharField(choices=[('neon', '#4fd8ff'), ('orange', '#ff9a3c'), ('green', '#a8e063'), ('neon2', '#8b7bff'), ('neon3', '#ff6cc4')], default='neon', max_length=20, verbose_name='رنگ شروع آواتار'),
        ),
    ]
