# Generated by Django 5.2.15 on 2026-09-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_categoryfeature_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='indexpagesettings',
            name='hero_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='indexpagesettings',
            name='hero_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='indexpagesettings',
            name='hero_mobile_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='indexpagesettings',
            name='hero_mobile_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, height_field='cover_image_height', help_text='تصویر اصلی مقاله که در هدر و کارت\u200cها نمایش داده می\u200cشود.\n📐 ابعاد: 1200 × 630 پیکسل (نسبت 1.91:1)\n📁 فرمت: WebP (بهترین) یا JPEG\n📦 حجم: حداکثر 200 کیلوبایت\n🖥️ رزولوشن: 72 DPI (مناسب برای وب)', null=True, upload_to='home/articles/', verbose_name='تصویر کاور', width_field='cover_image_width'),
        ),
        migrations.AlterField(
            model_name='indexpagesettings',
            name='hero_image',
            field=models.ImageField(blank=True, height_field='hero_image_height', help_text='تصویر اصلی هیرو (Desktop)\n📐 ابعاد: 1200 × 800 پیکسل\n📁 فرمت: WebP یا JPEG', null=True, upload_to='home/index/hero/', verbose_name='تصویر هیرو', width_field='hero_image_width'),
        ),
        migrations.AlterField(
            model_name='indexpagesettings',
            name='hero_mobile_image',
            field=models.ImageField(blank=True, height_field='hero_mobile_image_height', help_text='تصویر هیرو برای موبایل\n📐 ابعاد: 600 × 400 پیکسل', null=True, upload_to='home/index/hero/', verbose_name='تصویر هیرو موبایل', width_field='hero_mobile_image_width'),
        ),
    ]
