# Generated by Django 5.2.15 on 2026-09-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_article_cover_image_height_article_cover_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
    ]
