# Generated by Django 5.2.15 on 2026-07-04 15:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(blank=True, help_text='آیکون فونت\u200cآ\u200cوسم یا ایموجی', max_length=50, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='اسلاگ')),
                ('tagline', models.CharField(blank=True, help_text='یک عبارت کوتاه برای نمایش در هدر', max_length=255, verbose_name='شعار')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('cover_image', models.ImageField(help_text='تصویر اصلی محصول که در هدر نمایش داده می\u200cشود', upload_to='products/covers/', verbose_name='تصویر کاور')),
                ('cover_alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین تصویر کاور')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت (تومان)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='قیمت با تخفیف')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='آیکون فونت\u200cآ\u200cوسم یا ایموجی', max_length=50, verbose_name='آیکون')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('accent', models.CharField(blank=True, max_length=50, verbose_name='آیکون پس\u200cزمینه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_features', to='shop.product')),
            ],
            options={
                'verbose_name': 'ویژگی بازاریابی',
                'verbose_name_plural': 'ویژگی\u200cهای بازاریابی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='تصویر')),
                ('color_slug', models.SlugField(help_text='مثلاً: red, white, black, blue', verbose_name='اسلاگ رنگ')),
                ('color_label', models.CharField(help_text='مثلاً: قرمز, سفید, مشکی, آبی', max_length=50, verbose_name='نام رنگ')),
                ('color_hex', models.CharField(default='#FFFFFF', help_text='مثلاً: #D6483C', max_length=7, verbose_name='کد رنگ (Hex)')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان نظر')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('rejection_reason', models.TextField(blank=True, help_text='در صورت رد شدن نظر، دلیل آن را وارد کنید', verbose_name='دلیل رد شدن')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='تعداد مفید بودن')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='خرید تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر محصول',
                'verbose_name_plural': 'نظرات محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='آیکون فونت\u200cآ\u200cوسم یا ایموجی', max_length=50, verbose_name='آیکون')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
                ('label', models.CharField(max_length=100, verbose_name='برچسب')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='shop.product')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StatFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='عدد/مقدار')),
                ('suffix', models.CharField(blank=True, help_text='مثلاً: +, km, W, سال', max_length=20, verbose_name='پسوند')),
                ('label', models.CharField(max_length=100, verbose_name='برچسب')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_features', to='shop.product')),
            ],
            options={
                'verbose_name': 'آمار محصول',
                'verbose_name_plural': 'آمارهای محصول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='آیکون فونت\u200cآ\u200cوسم یا ایموجی', max_length=50, verbose_name='آیکون')),
                ('label', models.CharField(max_length=100, verbose_name='برچسب')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='مقدار')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_badges', to='shop.product')),
            ],
            options={
                'verbose_name': 'نشان اعتماد',
                'verbose_name_plural': 'نشان\u200cهای اعتماد',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cها',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
