# Generated by Django 5.2.15 on 2026-07-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryHeroProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_products', to='shop.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='shop.product')),
            ],
            options={
                'verbose_name': 'محصول اسلایدر',
                'verbose_name_plural': 'محصولات اسلایدر',
                'ordering': ['order'],
                'unique_together': {('category', 'product')},
            },
        ),
    ]
