# Generated by Django 5.2.15 on 2026-09-07 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر. اگر خالی باشد از توضیحات دسته\u200cبندی ساخته می\u200cشود.', max_length=160, verbose_name='توضیحات متا'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر. اگر خالی باشد از نام دسته\u200cبندی ساخته می\u200cشود.', max_length=60, verbose_name='عنوان متا'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='VOLTEX', max_length=100, verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='product',
            name='cover_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cover_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='محصولی که دیگر تولید/فروخته نمی\u200cشود. صفحه با ریدایرکت ۳۰۱ به محصول جایگزین یا به دسته\u200cبندی والد منتقل می\u200cشود تا ارزش لینک\u200cها از بین نرود.', verbose_name='تولید متوقف شده'),
        ),
        migrations.AddField(
            model_name='product',
            name='mpn',
            field=models.CharField(blank=True, max_length=64, verbose_name='شماره قطعه سازنده (MPN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='replacement_product',
            field=models.ForeignKey(blank=True, help_text='مقصد ریدایرکت ۳۰۱ برای محصول متوقف\u200cشده. اگر خالی باشد به دسته\u200cبندی می\u200cرود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='shop.product', verbose_name='محصول جایگزین'),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_expected',
            field=models.BooleanField(default=True, help_text='اگر تیک بخورد، صفحه\u200cی محصول ناموجود زنده و ایندکس\u200cشده می\u200cماند.', verbose_name='به\u200cزودی شارژ می\u200cشود'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='اگر خالی باشد به\u200cصورت خودکار ساخته می\u200cشود.', max_length=64, verbose_name='کد کالا (SKU)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_alt_text',
            field=models.CharField(blank=True, help_text='برای سئوی تصویر و دسترسی\u200cپذیری. اگر خالی باشد از نام محصول ساخته می\u200cشود.', max_length=200, verbose_name='متن جایگزین تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(height_field='cover_image_height', help_text='تصویر اصلی محصول که در هدر نمایش داده می\u200cشود', upload_to='products/covers/', verbose_name='تصویر کاور', width_field='cover_image_width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر. اگر خالی باشد از توضیحات محصول ساخته می\u200cشود.', max_length=160, verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر. اگر خالی باشد از نام محصول ساخته می\u200cشود.', max_length=60, verbose_name='عنوان متا'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='products/gallery/', verbose_name='تصویر', width_field='image_width'),
        ),
    ]
