# Generated by Django 5.2.15 on 2026-07-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_stock_out_at_cart_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_color',
            field=models.CharField(default='black', max_length=50, verbose_name='رنگ انتخاب\u200cشده'),
        ),
    ]
