# Generated by Django 4.2.30 on 2026-09-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_meta_description_category_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('snappay', 'اسنپ\u200cپی (اقساطی BNPL)'), ('digipay', 'دیجی\u200cپی'), ('idpay', 'آی\u200cدی\u200cپی'), ('nextpay', 'نکست\u200cپی'), ('sandbox', 'درگاه تستی (Sandbox)'), ('bank', 'بانکی')], max_length=20, verbose_name='درگاه پرداخت'),
        ),
    ]
