# Generated by Django 4.2.30 on 2026-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_transaction_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='NeX Go', max_length=100, verbose_name='برند'),
        ),
    ]
