# Generated by Django 5.2.15 on 2026-07-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cartitem_color_slug_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'ارسال معمولی'), ('express', 'ارسال فوری')], default='standard', max_length=20, verbose_name='روش ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مالیات'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='هزینه\u200cی خرید/تولید محصول — برای محاسبه\u200cی سود خالص استفاده می\u200cشود و به مشتری نمایش داده نمی\u200cشود', max_digits=15, verbose_name='قیمت تمام\u200cشده'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=30, unique=True, verbose_name='شناسه تراکنش')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آی\u200cدی\u200cپی'), ('nextpay', 'نکست\u200cپی'), ('bank', 'بانکی')], max_length=20, verbose_name='درگاه پرداخت')),
                ('reference_id', models.CharField(blank=True, help_text='Authority/RefID که خودِ درگاه برمی\u200cگرداند', max_length=100, verbose_name='کد رهگیری درگاه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل ناموفق بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تسویه')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shop.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ درخواستی')),
                ('reason', models.TextField(verbose_name='دلیل درخواست کاربر')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'بازگشت انجام شد')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_note', models.TextField(blank=True, help_text='در صورت رد شدن، دلیل رد شدن اینجا ثبت می\u200cشود', verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصمیم\u200cگیری')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='shop.order', verbose_name='سفارش')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='shop.transaction', verbose_name='تراکنش مرتبط')),
            ],
            options={
                'verbose_name': 'درخواست بازگشت وجه',
                'verbose_name_plural': 'درخواست\u200cهای بازگشت وجه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order', 'status'], name='shop_transa_order_i_3aed1a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['gateway', 'status'], name='shop_transa_gateway_b0c0e8_idx'),
        ),
    ]
