# Generated by Django 4.2.30 on 2026-09-15 17:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='کاربر همین کد را در سبد خرید وارد می\u200cکند. بزرگی و کوچکی حروف مهم نیست.', max_length=32, unique=True, verbose_name='کد تخفیف')),
                ('percentage', models.PositiveSmallIntegerField(help_text='عددی بین ۱ تا ۱۰۰', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, help_text='بیشترین تخفیفی که این کد می\u200cدهد (تومان). خالی یعنی بدون سقف.', max_digits=15, null=True, verbose_name='سقف مبلغ تخفیف')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, help_text='اگر مبلغ سبد خرید کمتر از این باشد کد پذیرفته نمی\u200cشود. صفر یعنی بدون محدودیت.', max_digits=15, verbose_name='حداقل مبلغ سبد خرید')),
                ('valid_from', models.DateTimeField(blank=True, help_text='خالی یعنی از همین حالا معتبر است.', null=True, verbose_name='شروع اعتبار')),
                ('valid_until', models.DateTimeField(blank=True, help_text='خالی یعنی تاریخ انقضا ندارد.', null=True, verbose_name='پایان اعتبار')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='مجموع دفعاتی که همه\u200cی کاربران می\u200cتوانند از این کد استفاده کنند. خالی یعنی نامحدود.', null=True, verbose_name='سقف کل دفعات استفاده')),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, help_text='مثلاً ۱ یعنی هر کاربر فقط یک\u200cبار. خالی یعنی نامحدود.', null=True, verbose_name='سقف استفاده برای هر کاربر')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='دفعات استفاده\u200cشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='متن کد در لحظه\u200cی ثبت سفارش؛ اگر بعداً کوپن حذف شود این باقی می\u200cماند.', max_length=32, verbose_name='کد تخفیف واردشده'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='تخفیف کد تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.coupon', verbose_name='کد تخفیف'),
        ),
    ]
