# Generated by Django 4.2.30 on 2026-08-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_shipping_method_order_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grid_image',
            field=models.ImageField(blank=True, help_text='تصویری که در کارت محصول داخل صفحه\u200cی دسته\u200cبندی نمایش داده می\u200cشود. اگر خالی بماند، از تصویر کاور استفاده می\u200cشود.', null=True, upload_to='products/grid/', verbose_name='تصویر گرید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(help_text='تصویر اصلی محصول که در صفحه\u200cی جزئیات نمایش داده می\u200cشود', upload_to='products/covers/', verbose_name='تصویر کاور'),
        ),
    ]
